//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageTrackerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        public int Carrier_ID { get; set; }
        public string Carrier_Name { get; set; }
        public string Email_Suffix { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
