//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageTrackerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Delivers = new HashSet<Deliver>();
            this.Receivers = new HashSet<Receiver>();
        }
    
        public int Package_ID { get; set; }
        public int Department_Karyakar_ID { get; set; }
        public int Courier_ID { get; set; }
        public int Shipper_ID { get; set; }
        public string BarCode { get; set; }
        public Nullable<System.DateTime> Date_Received { get; set; }
        public string Package_Received_By { get; set; }
        public byte[] Package_Image { get; set; }
        public string Image_Name { get; set; }
        public string Image_ContentType { get; set; }
        public string Comments { get; set; }
        public System.DateTime Create_Date { get; set; }
    
        public virtual Courier Courier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deliver> Delivers { get; set; }
        public virtual Department_Karyakar Department_Karyakar { get; set; }
        public virtual Shipper Shipper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receiver> Receivers { get; set; }
    }
}
