//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageTrackerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiver
    {
        public int Receiver_ID { get; set; }
        public int Package_ID { get; set; }
        public string Receiver_Name { get; set; }
        public string Receiver_Signature { get; set; }
        public string Comments { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
